### PR TITLE
Additional Parsers

### PR DESCRIPTION
**Pull request by bun-dev**
I added a parser for mixtape moe. It works identical to webmshare.
Tested it on my tumblr and it seems to work.
`@"https://my.mixtape.moe/" + mixtapeId + ".mp4";`

### CODE REVIEW

**Comment by bun-dev** [comment]
I attempted to add a parser for [MEGA](https://mega.nz/). Please note this still needs work. Since mega handles urls differently, I found it best to use an existing api to handle it. [MegaApiClient](https://github.com/gpailler/MegaApiClient). 

## To-do:
-Pipe the progress bar into the GUI.
Right now there's no progress indicator for when a file downloads from Mega. The api does however allow for a progress hook which I have tested and works. I just need to make it work for TumblThree.
-Bandwidth notification. Mega only allows users to download 2GB per x hours. I need a way for TumblThree to let the user know they've used up their bandwidth.
-Setup async downloading.  

screenshot 4

**Comment by bun-dev** [comment]
update#2
### Changes
-**Removed urlType**. Instead of having a urltype parameter, a simple check for mega urls in DownloadBinaryPost is made
-**Async downloading** for Mega.Reworked the mega parser to work with TumblThree's DownloadFileWithResumeAsync method by using the Stream from client.Download(link)
-Removed **ProgressionStream.cs**.

### -Possible Bug
-If a file is deleted from the tumblr site's download folder, it doesn't seem to redownload it because CheckIfFileExistsInDB(url) returns it as true. I''m not sure if I introduced this or not.

## To-do:
-wildcard selector for webmshare,mixtape moe and MEGA.
-bandwidth notification

**Comment by johanneszab** [comment]
> -Possible Bug
> 
> -If a file is deleted from the tumblr site's download folder, it doesn't seem to redownload it because CheckIfFileExistsInDB(url) returns it as true. I''m not sure if I introduced this or not.

No, it's wanted behavior. Now you can move your files (to a larger disk/NAS), leave the index in place and it will not download the same files twice. My initial thoughts implementing TumblThree was to safe download bandwidth, not so much disk space.

Why would you delete a file that you just downloaded, and then want to re-download it anyways? That doesn't make any sense for me. Of course, you're testing, there it's okay, but some people already complained about it and wanted a "re-download"-function. For that, you can simple remove the blog (index), and re-add it, but that seems to be too complicate for some people. If all the downloaded files are still in place, nothing will be re-downloaded, except for the missing files.

**Comment by johanneszab** [comment]
Okay, so, I'm not sure about this patch since it becomes larger and larger. At least it looks like you've some real interest in this project and I don't want to scare you away, since I'm currently writing a paper at work (and thus at home too) and am really low in time. It has to be somewhat finished in 4 weeks, and we're no point close to that.

* So, first I'm really glad that someone has interest in help programming, and not just opening new issues.
* I can give you full access to the repo, then we're at least two people contributing code. And as I've said above, I probably won't do much for the next month as well. Thus you can clean up your implementation and prepare a new release If you feel like the code is good. Or add something else to the code.
* I never really liked adding more and more external websites/parser. I do see that it makes sense feature wise and to make people happy, but it always felt like an endless story to me, since there will always be someone that wants a different site to be added. So, if you want to do it, that's great. I think It doesn't make much sense me interfering with your code here anyways while you're still implementing things (mega, google, ..). I mean, it's not that there isn't anything else to do ;). I can do one of the several other issues/request then like the file renamer.
* Just make sure the code isn't getting too messy.
* How big is the zip now with all the external libraries?
* Can make your resharper code guidelines team-wide and add then to the solution? I actually used our work template [here](https://github.com/johanneszab/TumblThree/commit/6d5431393b7d11a8b9bb8468c6f259a6d1a132c7) shortly, but didn't add it to TumblThree. Maybe it's better to add one otherwise someone else will come and force down it's template and the commits getting full with code style changes.

So, thanks again for your already made contribution!

**Comment by johanneszab** [comment]
I've made a [new branch](https://github.com/johanneszab/TumblThree/tree/parser) for the mega and google drive parser as there was still some work to do and I wanted a new release that fixes the proxy issue (#204).

**Pull request merged**
