### PR TITLE
Emphasia's translation

### PR DESCRIPTION
**Pull request by Emphasia**

### CODE REVIEW

**Comment by johanneszab** [comment]
Thanks again!

**Comment by Emphasia** [comment]
[Presentation - Resources.zh.resx](https://github.com/Emphasia/TumblThree/blob/Emphasia-translation/src/TumblThree/TumblThree.Presentation/Properties/Resources.zh.resx)
[Applications - Resources.zh.resx](https://github.com/Emphasia/TumblThree/blob/Emphasia-translation/src/TumblThree/TumblThree.Applications/Properties/Resources.zh.resx)
did some minor changes after trying out the new version.

**Comment by johanneszab** [comment]
Thanks. I'll update it once I've time.

**Comment by Emphasia** [comment]
[Update Chinese translation for TumblThree v1.0.8.20.zip](https://github.com/johanneszab/TumblThree/files/1276096/Update.Chinese.translation.for.TumblThree.v1.0.8.20.zip)

**Comment by johanneszab** [comment]
Thanks. I'll update with in the next release.

**Comment by Emphasia** [comment]
I've put both the source files and translation files [here](https://github.com/Emphasia/TumblThree-zh) to avoid annoying you, or is it more convenient for you that I leave messages here every time there's an update?

**Comment by johanneszab** [comment]
No, it's perfect as it is. I like you own project containing all the translations, and I'll regularly update the main application. I just haven't had time to properly do it yet.

I'll also link to your translated readme in the TumblThree readme itself!

Thanks for all the continuous work. I really appreciate it.

**Pull request merged**
