### PR TITLE
Update Resources.zh.resx

### PR DESCRIPTION
**Pull request by Emphasia**
I corrected some translations that bothers me when I'm using it and add some other key translations.
I'm not sure what "Enqueue selection" & "Number Of Downloads" does, so I left them untranslated.
This is a rough version and I will try to finish a more complete version.

### CODE REVIEW

**Comment by johanneszab** [comment]
Thanks a lot!

I'll update the release once you're done. There is also a translation file for the application layer in TumblThree.Applications/Properties/Resources.zh.resx, which isn't that important compared to the one you've already covered, but if you have time at some point, I'd be happy if you'd correct it. But don't feel any pressured.

I just wish right now I'd have done an Indian google translate translation too. Maybe someone would have come forward to fix that too. That would probably have most people covered.

Since I've no clue about your language there, does it make sense to include a traditional Chinese translation as well?

Thanks again!

**Comment by Emphasia** [comment]
I am not quite familiar with traditional Chinese, and from my experience, Google can do a better job than me at delivering a simplified Chinese to traditional Chinese translation, and there should be no big problems in it when using simplified Chinese as a mediation.
As for the rest of the "ToolTip" and "application layer" part, I think I can finish most of them but there may be some difficulty with the rest because I do not know exactly their context (just like Google) and can only take a guess, so I can make the translation more coherent but may not be able to deliver a more accurate translation than Google. Maybe when I come across them in actual use sometime, I'll be able to correct them.

**Comment by Emphasia** [comment]
Sorry, I think I clicks the Close button accidentally.

**Comment by Emphasia** [comment]
a complete one. #123

**Pull request closed without merging**
