### PR TITLE
Create axolotlc.tumblr.com

### PR DESCRIPTION
**Pull request by Orimar6**

### CODE REVIEW

**Comment by gpriaulx** [comment]
I don't get it? What am I missing? :|

**Comment by Hrxn** [comment]
Bot spam?

**Comment by johanneszab** [comment]
I was also wondering this the last time someone submitted a pull request like this.

On the other hand, .. who knows what kind of buttons people press without knowing what they are actually doing..

**Comment by gpriaulx** [comment]
It's like he made an account especially to do it. Such dedication. Such passion.

**Pull request closed without merging**
